# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-16 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('relation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='InsiderTrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateField()),
                ('trans_type', models.CharField(max_length=70)),
                ('owner_type', models.CharField(max_length=40)),
                ('shares_traded', models.FloatField()),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('shares_held', models.IntegerField()),
                ('company_alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot_app.Company')),
                ('insider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot_app.Insider')),
            ],
        ),
    ]
